backend:
  name: github
  repo: roadlittledawn/gatsby-netlify-cms-example

media_folder: static/assets

publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  
  - name: release-notes
    label: Release Notes
    label_singular: Release Note
    description: "Release notes for all downloaded New Relic software."
    folder: release-notes-agents
    create: true
    slug: "release-notes-agent/{{slug}}"
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: "download-url", label: "Download URL", widget: "string", pattern: ["https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)", "Must be valid URL syntax beginning with http/https and ending with .com"]}
      - { name: product-categories, label: Product Categories, widget: select, multiple: true, options: ["APM", "Browser", "Infrastructure", "Mobile"] }
