backend:
  name: github
  branch: add-docs-collections
  repo: roadlittledawn/gatsby-netlify-cms-example
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

publish_mode: editorial_workflow
media_folder: src/images
public_folder: /img

collections:
  - name: 'guide'
    label: 'Guide'
    folder: 'src/content'
    create: true
    slug: '{{slug}}'
    path: '{{folder}}/{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'GuideTemplate',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Duration', name: 'duration', widget: 'string' }
      - { label: 'Folder', name: 'folder', widget: 'string' }
      - { label: 'Path', name: 'path', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'doc-page'
    label: 'Basic Doc Page'
    folder: 'src/content/doc-pages'
    create: true
    slug: '{{slug}}'
    path: '{{folder-1}}/{{folder-2}}/{{folder-3}}/{{slug}}'
    fields:
     - {
         label: 'Template Key',
         name: 'templateKey',
         widget: 'hidden',
         default: 'BasicDocPageTemplate',
       }
     - { label: 'Title', name: 'title', widget: 'string' }
     - { label: 'Path', name: 'path', widget: 'string' }
     - {
         label: 'Topic',
         name: 'topic',
         widget: 'select',
         multiple: true,
         required: false,
         options: [{label: 'APM', value: 'apm'}, {label: 'Mobile Monitoring', value: 'mobile-monitoring'}]
       }
     - { label: 'Body', name: 'body', widget: 'markdown' }
